name: explore
description: Explore.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.4
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png

  fonts:
   - family: tectonica
     fonts:
      - asset: fonts/tectonica-swash.otf

   - family: Axiforma
     fonts:
      - asset: fonts/Axiforma.ttf
